#!/usr/bin/env python3
"""custom-report-pdf.py — ReportLab generator for Phase A3 custom reports.

Invoked by src/lib/custom-report-export.ts via `execFileSync`:

    python3 scripts/custom-report-pdf.py <payload.json> <output.pdf>

The payload JSON shape:
    {
      "title": str,
      "description": str | null,
      "generatedAt": str (ISO),
      "generatedBy": str,
      "dataSource": "devices" | "workorders" | "meterreadings" | "stockitems",
      "columns": [{ "key": str, "label": str }, ...],
      "rows": [{ "<key>": "<string value>", ... }, ...],
      "total": int,
      "truncated": bool
    }

Design:
  • Cover page is skipped (per `report.md`: "Skip cover only for: resumes,
    letters, memos, forms, checklists, or documents ≤ 2 pages"). Custom
    reports are typically 1-3 page tables, so cover is skipped.
  • Thai support: register Loma (TLWG) — a Thai-aware TTF shipped with
    Debian/Ubuntu's `fonts-tlwg` package — for body + headings. Falls
    back to Helvetica if registration fails.
  • Page numbers in the footer.
  • Filter summary table on the first page (filterable fields + ops).
"""

import json
import os
import sys
from datetime import datetime

# Make the pdf skill's helper modules importable (optional — we don't need them
# for this self-contained generator, but keeping the path set lets us use the
# skill's palette generator if we ever want to switch).
PDF_SKILL_DIR = os.environ.get('PDF_SKILL_DIR', '/home/z/my-project/skills/pdf')

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


# ── Font registration ────────────────────────────────────────────────

FONT_REGULAR = 'Helvetica'
FONT_BOLD = 'Helvetica-Bold'

_FONT_PATHS = [
    # Thai-capable fonts shipped on the sandbox (Debian fonts-tlwg + FreeFont).
    ('Loma', '/usr/share/fonts/opentype/tlwg/Loma.otf'),
    ('Loma-Bold', '/usr/share/fonts/opentype/tlwg/Loma-Bold.otf'),
    ('FreeSans', '/usr/share/fonts/truetype/freefont/FreeSans.ttf'),
    ('FreeSans-Bold', '/usr/share/fonts/truetype/freefont/FreeSansBold.ttf'),
    ('DejaVu', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'),
    ('DejaVu-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'),
]

def register_fonts() -> None:
    global FONT_REGULAR, FONT_BOLD
    registered = []
    for name, path in _FONT_PATHS:
        if not os.path.exists(path):
            continue
        try:
            pdfmetrics.registerFont(TTFont(name, path))
            registered.append((name, path))
        except Exception:
            pass  # try the next fallback
    # Pick the first pair that has both Regular + Bold.
    for reg_name, _ in registered:
        bold_name = reg_name + '-Bold'
        if any(n == bold_name for n, _ in registered):
            FONT_REGULAR = reg_name
            FONT_BOLD = bold_name
            break

register_fonts()


# ── Palette ──────────────────────────────────────────────────────────
# A muted, professional palette suitable for tabular reports.
# Derived manually (we don't run palette.cascade here — this generator is
# called inside Next.js server runtime, not by the LLM).

PAGE_BG       = colors.HexColor('#ffffff')
SECTION_BG    = colors.HexColor('#f5f4f3')
CARD_BG       = colors.HexColor('#f0efed')
TABLE_STRIPE  = colors.HexColor('#edebe8')
HEADER_FILL   = colors.HexColor('#3d5a6e')
BORDER        = colors.HexColor('#b8c0c7')
ACCENT        = colors.HexColor('#2f97b9')
TEXT_PRIMARY  = colors.HexColor('#252422')
TEXT_MUTED    = colors.HexColor('#8d8981')


# ── Page geometry ────────────────────────────────────────────────────

PAGE_SIZE = landscape(A4)  # 297mm x 210mm — wide format for data tables
LEFT_MARGIN = 15 * mm
RIGHT_MARGIN = 15 * mm
TOP_MARGIN = 18 * mm
BOTTOM_MARGIN = 18 * mm


# ── Footer (page numbers) ─────────────────────────────────────────────

class NumberedDocTemplate(SimpleDocTemplate):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._page_count = 0

    def afterPage(self):
        # Hook point — footer drawn via canvas in `onPage` callback.
        pass


def _draw_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont(FONT_REGULAR, 8)
    canvas.setFillColor(TEXT_MUTED)
    page_w, _ = PAGE_SIZE
    footer_y = 8 * mm
    canvas.drawString(
        LEFT_MARGIN,
        footer_y,
        'Generated by ITAM-NextJS Custom Report Builder',
    )
    page_text = f'Page {doc.page}'
    canvas.drawRightString(
        page_w - RIGHT_MARGIN,
        footer_y,
        page_text,
    )
    canvas.restoreState()


# ── Main builder ──────────────────────────────────────────────────────

def build_pdf(payload: dict, output_path: str) -> None:
    title = payload.get('title', 'Custom Report')
    description = payload.get('description') or ''
    generated_at = payload.get('generatedAt', '')
    generated_by = payload.get('generatedBy', '')
    data_source = payload.get('dataSource', 'unknown')
    columns = payload.get('columns', [])
    rows = payload.get('rows', [])
    total = payload.get('total', len(rows))
    truncated = payload.get('truncated', False)

    # Try to render the timestamp in a friendly way.
    try:
        dt = datetime.fromisoformat(generated_at.replace('Z', '+00:00'))
        generated_str = dt.strftime('%Y-%m-%d %H:%M:%S UTC')
    except Exception:
        generated_str = generated_at

    # Cap rows to 500 to keep the PDF sane. PDFs are not spreadsheets.
    # The caller has already enforced a server-side limit, but we cap again.
    PDF_ROW_CAP = 500
    rows_capped = rows[:PDF_ROW_CAP]
    rows_truncated_pdf = len(rows) > PDF_ROW_CAP

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Title'],
        fontName=FONT_BOLD,
        fontSize=18,
        leading=22,
        textColor=TEXT_PRIMARY,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=9,
        leading=12,
        textColor=TEXT_MUTED,
        spaceAfter=12,
    )
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName=FONT_BOLD,
        fontSize=9,
        leading=12,
        textColor=TEXT_PRIMARY,
    )
    meta_value_style = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=9,
        leading=12,
        textColor=TEXT_PRIMARY,
    )
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName=FONT_BOLD,
        fontSize=11,
        leading=14,
        textColor=HEADER_FILL,
        spaceBefore=10,
        spaceAfter=4,
    )
    cell_style = ParagraphStyle(
        'Cell',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=8,
        leading=10,
        textColor=TEXT_PRIMARY,
    )
    header_cell_style = ParagraphStyle(
        'HeaderCell',
        parent=styles['Normal'],
        fontName=FONT_BOLD,
        fontSize=8,
        leading=10,
        textColor=colors.white,
    )
    description_style = ParagraphStyle(
        'Description',
        parent=styles['Normal'],
        fontName=FONT_REGULAR,
        fontSize=9,
        leading=12,
        textColor=TEXT_PRIMARY,
        spaceAfter=8,
    )

    story = []

    # ── Title block ──────────────────────────────────────────────────
    story.append(Paragraph(_escape(title), title_style))
    story.append(Paragraph(
        f'Custom Report &middot; data source: <b>{_escape(data_source)}</b>',
        subtitle_style,
    ))

    # ── Meta table (Generated At / Generated By / Total Rows / Status) ─
    meta_rows = [
        [
            Paragraph('Generated At', meta_label_style),
            Paragraph(_escape(generated_str), meta_value_style),
            Paragraph('Generated By', meta_label_style),
            Paragraph(_escape(generated_by or 'system'), meta_value_style),
        ],
        [
            Paragraph('Data Source', meta_label_style),
            Paragraph(_escape(data_source), meta_value_style),
            Paragraph('Total Rows', meta_label_style),
            Paragraph(f'{total} (showing {len(rows_capped)})', meta_value_style),
        ],
    ]
    page_w, _ = PAGE_SIZE
    avail_w = page_w - LEFT_MARGIN - RIGHT_MARGIN
    meta_col_w = [avail_w * 0.18, avail_w * 0.32, avail_w * 0.18, avail_w * 0.32]
    meta_table = Table(meta_rows, colWidths=meta_col_w, hAlign='LEFT')
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 8))

    # ── Description (optional) ────────────────────────────────────────
    if description:
        story.append(Paragraph('Description', section_heading_style))
        story.append(Paragraph(_escape(description), description_style))

    # ── Truncation notice ────────────────────────────────────────────
    notice_parts = []
    if truncated:
        notice_parts.append(
            f'Result truncated at the server-side limit. Total rows matching the filter: {total}. '
            'Adjust the report limit or filter to see more rows.'
        )
    if rows_truncated_pdf:
        notice_parts.append(
            f'Only the first {PDF_ROW_CAP} rows are rendered in the PDF (out of {len(rows)}). '
            'Export as CSV for the full dataset.'
        )
    if notice_parts:
        notice_text = ' &nbsp;|&nbsp; '.join(notice_parts)
        story.append(Paragraph(
            f'<b>Note:</b> {notice_text}',
            ParagraphStyle(
                'Notice',
                parent=styles['Normal'],
                fontName=FONT_REGULAR,
                fontSize=9,
                leading=12,
                textColor=ACCENT,
                spaceAfter=8,
            ),
        ))

    # ── Data table ───────────────────────────────────────────────────
    story.append(Paragraph('Data', section_heading_style))

    if not columns or not rows_capped:
        story.append(Paragraph(
            '<i>No rows matched the report configuration.</i>',
            description_style,
        ))
    else:
        # Build header row.
        header_cells = [
            Paragraph(_escape(col.get('label', col.get('key', ''))), header_cell_style)
            for col in columns
        ]
        # Build body cells. Each cell is wrapped in a Paragraph so long text wraps
        # instead of overflowing the column width.
        body_rows = []
        for row in rows_capped:
            body_cells = []
            for col in columns:
                key = col.get('key', '')
                raw = row.get(key, '')
                text = _escape(str(raw)) if raw is not None else ''
                body_cells.append(Paragraph(text, cell_style))
            body_rows.append(body_cells)

        # Distribute column widths proportional to label length, with a floor.
        label_lens = [max(len(col.get('label', col.get('key', ''))), 6) for col in columns]
        total_label = sum(label_lens)
        col_widths = [
            max(20 * mm, (length / total_label) * avail_w)
            for length in label_lens
        ]
        # Trim if the total exceeds the available width (proportional shrink).
        scale = avail_w / sum(col_widths)
        if scale < 1.0:
            col_widths = [w * scale for w in col_widths]

        table_data = [header_cells] + body_rows
        table = Table(table_data, colWidths=col_widths, repeatRows=1, hAlign='LEFT')

        style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), FONT_BOLD),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('FONTNAME', (0, 1), (-1, -1), FONT_REGULAR),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
            ('LINEBELOW', (0, 0), (-1, 0), 0.75, HEADER_FILL),
            ('INNERGRID', (0, 1), (-1, -1), 0.25, BORDER),
        ]
        # Alternating row stripes.
        for i in range(1, len(table_data)):
            if i % 2 == 0:
                style_cmds.append(('BACKGROUND', (0, i), (-1, i), TABLE_STRIPE))
            else:
                style_cmds.append(('BACKGROUND', (0, i), (-1, i), colors.white))
        table.setStyle(TableStyle(style_cmds))
        story.append(table)

    # ── Build ────────────────────────────────────────────────────────
    doc = SimpleDocTemplate(
        output_path,
        pagesize=PAGE_SIZE,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title=title,
        author='ITAM-NextJS',
        subject='Custom Report',
        creator='ITAM-NextJS Custom Report Builder',
    )
    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)


def _escape(text: str) -> str:
    """Escape XML-special characters for ReportLab Paragraphs."""
    if text is None:
        return ''
    return (
        str(text)
        .replace('&', '&amp;')
        .replace('<', '&lt;')
        .replace('>', '&gt;')
    )


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.stderr.write('Usage: custom-report-pdf.py <payload.json> <output.pdf>\n')
        sys.exit(2)
    json_path = sys.argv[1]
    out_path = sys.argv[2]
    with open(json_path, 'r', encoding='utf-8') as f:
        payload = json.load(f)
    build_pdf(payload, out_path)
